"""remove legacy attendance fields

Revision ID: e2da03310bec
Revises: c671e1a269fc
Create Date: 2026-08-23 23:21:30.097542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2da03310bec'
down_revision: Union[str, Sequence[str], None] = 'c671e1a269fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'punch_out_time')
    op.drop_column('attendances', 'entry_2_time')
    op.drop_column('attendances', 'entry_1_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('entry_1_time', sa.DATETIME(), nullable=True))
    op.add_column('attendances', sa.Column('entry_2_time', sa.DATETIME(), nullable=True))
    op.add_column('attendances', sa.Column('punch_out_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
